import {
  encrypt,
  encodePayload,
  decrypt,
  decodePayload,
  deriveKeyFromSignature,
} from "./crypto";

let _agentInitialized = false;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _fileverseAgent: any = null;

async function getFileverseAgent() {
  if (_fileverseAgent && _agentInitialized) return _fileverseAgent;

  const { Agent } = await import("@fileverse/agents");
  const { PinataStorageProvider } = await import("@fileverse/agents/storage");
  const { privateKeyToAccount } = await import("viem/accounts");

  const storageProvider = new PinataStorageProvider({
    jwt: process.env.PINATA_JWT!,
    gateway: process.env.PINATA_GATEWAY!,
  });

  _fileverseAgent = new Agent({
    chain: "gnosis",
    viemAccount: privateKeyToAccount(
      process.env.FILEVERSE_PRIVATE_KEY as `0x${string}`
    ),
    pimlicoAPIKey: process.env.PIMLICO_API_KEY!,
    storageProvider,
  });

  await _fileverseAgent.setupStorage("obscura-reports");
  _agentInitialized = true;
  return _fileverseAgent;
}

export async function createEncryptedReport(
  title: string,
  content: string,
  userSignature: string
): Promise<{ fileId: string; encryptedContent: string }> {
  const agent = await getFileverseAgent();
  const key = deriveKeyFromSignature(userSignature);

  const markdown = `# ${title}\n\n${content}\n\n---\n*Generated by Obscura at ${new Date().toISOString()}*`;
  const payload = encrypt(markdown, key);
  const encoded = encodePayload(payload);

  const report = await agent.create(encoded);
  return { fileId: report.fileId, encryptedContent: encoded };
}

export async function readEncryptedReport(
  fileId: string,
  userSignature: string
): Promise<string> {
  const agent = await getFileverseAgent();
  const data = await agent.getFile(fileId);
  const key = deriveKeyFromSignature(userSignature);
  const payload = decodePayload(data.content);
  return decrypt(payload, key);
}

export async function createPlaintextReport(
  title: string,
  content: string
): Promise<{ fileId: string }> {
  const agent = await getFileverseAgent();
  const markdown = `# ${title}\n\n${content}\n\n---\n*Generated by Obscura at ${new Date().toISOString()}*`;
  const report = await agent.create(markdown);
  return { fileId: report.fileId };
}
