import {
  encrypt,
  encodePayload,
  decrypt,
  decodePayload,
  deriveKeyFromSignature,
} from "./crypto";

// --- Fileverse REST API (ddocs.new) ---

function getApiConfig(): { baseUrl: string; apiKey: string } | null {
  const apiKey = process.env.FILEVERSE_API_KEY;
  const baseUrl = process.env.FILEVERSE_API_URL || "http://localhost:8001";
  if (!apiKey) return null;
  return { baseUrl, apiKey };
}

async function apiCreateDocument(
  title: string,
  content: string
): Promise<{ ddocId: string }> {
  const config = getApiConfig();
  if (!config) throw new Error("FILEVERSE_API_KEY not set");

  const res = await fetch(`${config.baseUrl}/api/ddocs?apiKey=${config.apiKey}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ title, content }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Fileverse API create failed (${res.status}): ${text}`);
  }

  const data = await res.json();
  return { ddocId: data.ddocId || data.id || data._id };
}

async function apiGetDocument(
  ddocId: string
): Promise<{ title: string; content: string }> {
  const config = getApiConfig();
  if (!config) throw new Error("FILEVERSE_API_KEY not set");

  const res = await fetch(
    `${config.baseUrl}/api/ddocs/${ddocId}?apiKey=${config.apiKey}`
  );

  if (!res.ok) {
    throw new Error(`Fileverse API read failed (${res.status})`);
  }

  return res.json();
}

// --- Public API (used by agents) ---

export async function createEncryptedReport(
  title: string,
  content: string,
  userSignature: string,
  salt: string = ""
): Promise<{ fileId: string; encryptedContent: string }> {
  const key = deriveKeyFromSignature(userSignature, salt);
  const markdown = `# ${title}\n\n${content}\n\n---\n*Generated by Obscura at ${new Date().toISOString()}*`;
  const payload = encrypt(markdown, key);
  const encoded = encodePayload(payload);

  // Try Fileverse REST API first, then agents SDK
  if (getApiConfig()) {
    try {
      const result = await apiCreateDocument(`[Obscura] ${title}`, encoded);
      return { fileId: `ddoc:${result.ddocId}`, encryptedContent: encoded };
    } catch {
      // REST API unavailable — fall through to agents SDK
    }
  }

  const agent = await getFileverseAgent();
  const report = await agent.create(encoded);
  return { fileId: report.fileId, encryptedContent: encoded };
}

export async function readEncryptedReport(
  fileId: string,
  userSignature: string,
  salt: string = ""
): Promise<string> {
  const key = deriveKeyFromSignature(userSignature, salt);

  // Handle ddoc: prefix (REST API documents)
  if (fileId.startsWith("ddoc:")) {
    const ddocId = fileId.slice(5);
    const doc = await apiGetDocument(ddocId);
    const payload = decodePayload(doc.content);
    return decrypt(payload, key);
  }

  // Fallback: old SDK
  const agent = await getFileverseAgent();
  const data = await agent.getFile(fileId);
  const payload = decodePayload(data.content);
  return decrypt(payload, key);
}

// --- Legacy @fileverse/agents SDK fallback ---

let _agentInitialized = false;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _fileverseAgent: any = null;

async function getFileverseAgent() {
  if (_fileverseAgent && _agentInitialized) return _fileverseAgent;

  const { Agent } = await import("@fileverse/agents");
  const { PinataStorageProvider } = await import("@fileverse/agents/storage");
  const { privateKeyToAccount } = await import("viem/accounts");

  const storageProvider = new PinataStorageProvider({
    jwt: process.env.PINATA_JWT!,
    gateway: process.env.PINATA_GATEWAY!,
  });

  _fileverseAgent = new Agent({
    chain: "gnosis",
    viemAccount: privateKeyToAccount(
      process.env.FILEVERSE_PRIVATE_KEY as `0x${string}`
    ),
    pimlicoAPIKey: process.env.PIMLICO_API_KEY!,
    storageProvider,
  });

  await _fileverseAgent.setupStorage("obscura-reports");
  _agentInitialized = true;
  return _fileverseAgent;
}
